version: '2'
services:
    web:
        build: .
        command: flask run --host 0.0.0.0 --port 5000
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
          migrator_test:
            condition: service_completed_successfully

    mvp_database:
      image: postgres:13-alpine
      ports:
        - "4444:5432"
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=mvpdb
      volumes:
        - database_data:/var/lib/postgresql/data
      healthcheck:
        test:
          - CMD-SHELL
          - pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB
        interval: 5s
        timeout: 10s
        retries: 5

    migrator_test:
      platform: linux/amd64
      build:
        dockerfile: Dockerfile
        context: .
      command: flask db upgrade
      volumes:
        - ./migrations:/app/migrations
      depends_on:
        mvp_database:
          condition: service_healthy

volumes:
  database_data:
  notused:
