"""A

Revision ID: 9b37682d2abf
Revises: 735313da27b1
Create Date: 2022-11-12 15:59:40.056440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b37682d2abf"
down_revision = "735313da27b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_loggedin", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_loggedin")
    # ### end Alembic commands ###
